services:
  - type: web
    name: stagemarkt
    env: php
    region: frankfurt
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://stagemarkt.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: stagemarkt-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: stagemarkt-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: stagemarkt-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: stagemarkt-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stagemarkt-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: stagemarkt-db
    databaseName: stagemarkt
    user: stagemarkt_user